<?php
namespace backend\components;

use Yii;

class Controller extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            $this->redirect('/site/login');
            return false;
        }
        $user = Yii::$app->user->identity;
        if($user->status <= 0){
            $this->redirect('/site/logout');
            return false;
        }
        if($user->ga_secret == ''){
            $this->redirect('/site/bind');
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    protected function renderJSON($data=[], $msg ="ok", $code = 200)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        \Yii::$app->response->data = [
            "code" => $code,
            "msg"   =>  $msg,
            "data"  =>  $data,
            "req_id" =>  uniqid(),
        ];

        return \Yii::$app->response;
    }
}