<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 2021/9/16
 * Time: 16:52
 */

namespace api\modules\contents;

class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}